language: node_js
node_js:
  - "lts/dubnium"

install:
  - npm install

script:
  - npm run compile
  - npm run test
  - npm install
  - cd samples
  - npm install
  - npm test

deploy:
  provider: npm
  email: "${CI_EMAIL}"
  api_key: "${CI_API_KEY}"
  on:
    tags: true
