language: node_js
node_js:
  - 'lts/dubnium'

install:
  - yarn install

script:
  - ./build.sh

deploy:
  provider: npm
  email: '${CI_EMAIL}'
  api_key: '${CI_API_KEY}'
  skip_cleanup: true
  on:
    tags: true
