language: node_js
node_js:
  - 'lts/erbium'

install:
#  - echo "//registry.npmjs.org/:_authToken=${CI_TOKEN}" > ~/.npmrc
  - yarn install

script:
  - ./build.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
