language: node_js
node_js:
  - "lts/dubnium"

install:
  - npm install

script:
  - ./build.sh
  - cd samples
  - npm install
  - npm test
  - cd ..

deploy:
  provider: npm
  email: "${CI_EMAIL}"
  api_key: "${CI_API_KEY}"
  skip_cleanup: true
  on:
    tags: true
