# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:erbium

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: ./build.sh

  deploy:
    <<: *defaults
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          requires:
            - build
        filters:
          tags:
            only: /\d+\.\d+\.\d+/

